// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PracticalMicroservices.MaterializedViews.Infrastructure;

namespace PracticalMicroservices.MaterializedViews.Migrations
{
    [DbContext(typeof(MaterializedViewsContext))]
    [Migration("20211220111834_AddGlobalPositionToPage")]
    partial class AddGlobalPositionToPage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PracticalMicroservices.Views.Entities.Page", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<long>("GlobalPosition")
                        .HasColumnType("bigint");

                    b.HasKey("Name");

                    b.ToTable("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
